import { Prisma, ReviewSource } from "@prisma/client";
import { ReviewRepository, type ReviewQuery } from "../repositories/review.repository";
import { CompanyService } from "./company.service";
import { AuditService } from "./audit.service";
import { NotFoundError, ValidationError, AppError } from "../utils/errors";
import { env } from "../config/env";
import { logger } from "../config/logger";

export interface ReviewInput {
  source: ReviewSource;
  authorName: string;
  authorRole?: string | null;
  rating: number;
  text: string;
  reviewDate?: string | Date;
  sourceUrl?: string | null;
  isPublished?: boolean;
  sortOrder?: number;
}

/** Shape returned by the Google Places "place details" endpoint, narrowed to what we use. */
interface GooglePlacesReview {
  author_name?: string;
  rating?: number;
  text?: string;
  time?: number;
  author_url?: string;
  relative_time_description?: string;
}

/**
 * Customer reviews shown on the public website.
 *
 * Reviews are never generated by the application. They arrive one of two ways:
 *
 *   1. An admin enters a real review, attributed and linked to its listing.
 *   2. The Google Places API returns them, when a key and place id are configured.
 *
 * JustDial publishes no API, so its reviews are entered by hand with a link back
 * to the listing.
 */
export class ReviewService {
  constructor(
    private reviewRepository: ReviewRepository,
    private companyService: CompanyService,
    private auditService: AuditService,
  ) {}

  list(query: ReviewQuery) {
    return this.reviewRepository.list(query);
  }

  /** Published reviews plus the aggregate rating — what the public website renders. */
  async published() {
    const [{ rows }, summary] = await Promise.all([
      this.reviewRepository.list({ isPublished: true, take: 60 }),
      this.reviewRepository.summary(),
    ]);
    const company = await this.companyService.getOrNull();

    return {
      reviews: rows,
      summary,
      links: {
        google: company?.googleMapsUrl ?? null,
        justdial: company?.justdialUrl ?? null,
      },
    };
  }

  async getById(id: string) {
    const review = await this.reviewRepository.findById(id);
    if (!review) throw new NotFoundError("Review not found");
    return review;
  }

  async create(input: ReviewInput) {
    const review = await this.reviewRepository.create(this.toPersistable(input));
    await this.auditService.record("UPDATE_COMPANY_SETTINGS", {
      entityType: "Review",
      entityId: review.id,
      newValues: { action: "created", author: review.authorName, source: review.source },
    });
    return review;
  }

  async update(id: string, input: Partial<ReviewInput>) {
    await this.getById(id);

    const data: Prisma.ReviewUpdateInput = {
      ...(input.source !== undefined ? { source: input.source } : {}),
      ...(input.authorName !== undefined ? { authorName: input.authorName } : {}),
      ...(input.authorRole !== undefined ? { authorRole: input.authorRole } : {}),
      ...(input.rating !== undefined ? { rating: this.assertRating(input.rating) } : {}),
      ...(input.text !== undefined ? { text: input.text } : {}),
      ...(input.reviewDate !== undefined ? { reviewDate: new Date(input.reviewDate) } : {}),
      ...(input.sourceUrl !== undefined ? { sourceUrl: input.sourceUrl } : {}),
      ...(input.isPublished !== undefined ? { isPublished: input.isPublished } : {}),
      ...(input.sortOrder !== undefined ? { sortOrder: input.sortOrder } : {}),
    };

    return this.reviewRepository.update(id, data);
  }

  async remove(id: string) {
    const review = await this.getById(id);
    await this.reviewRepository.delete(id);
    await this.auditService.record("UPDATE_COMPANY_SETTINGS", {
      entityType: "Review",
      entityId: id,
      oldValues: { author: review.authorName, source: review.source },
      newValues: { action: "deleted" },
    });
  }

  /** Whether automatic Google sync is available on this deployment. */
  async googleSyncStatus(): Promise<{ configured: boolean; missing: string[] }> {
    const company = await this.companyService.getOrNull();
    const missing: string[] = [];
    if (!env.GOOGLE_PLACES_API_KEY) missing.push("GOOGLE_PLACES_API_KEY environment variable");
    if (!company?.googlePlaceId) missing.push("Google Place ID in company settings");
    return { configured: missing.length === 0, missing };
  }

  /**
   * Pull reviews from the Google Places API.
   *
   * Google returns at most five reviews per place and does not page, so this
   * tops up what is already stored rather than replacing it. Rows are keyed by
   * a stable external id so repeat syncs update in place.
   */
  async syncFromGoogle(): Promise<{ imported: number; total: number }> {
    const status = await this.googleSyncStatus();
    if (!status.configured) {
      throw new ValidationError(
        `Google review sync is not configured. Add: ${status.missing.join("; ")}.`,
      );
    }

    const company = await this.companyService.get();
    const url = new URL("https://maps.googleapis.com/maps/api/place/details/json");
    url.searchParams.set("place_id", company.googlePlaceId!);
    url.searchParams.set("fields", "review,rating,user_ratings_total");
    url.searchParams.set("reviews_sort", "newest");
    url.searchParams.set("key", env.GOOGLE_PLACES_API_KEY!);

    const response = await fetch(url, { signal: AbortSignal.timeout(15_000) }).catch((error: unknown) => {
      logger.error({ err: error }, "Google Places request failed");
      throw new AppError("Could not reach the Google Places API", 502);
    });

    if (!response.ok) {
      throw new AppError(`Google Places API returned ${response.status}`, 502);
    }

    const payload = (await response.json()) as {
      status?: string;
      error_message?: string;
      result?: { reviews?: GooglePlacesReview[] };
    };

    if (payload.status && payload.status !== "OK") {
      throw new AppError(`Google Places API: ${payload.error_message ?? payload.status}`, 502);
    }

    const reviews = payload.result?.reviews ?? [];
    let imported = 0;

    for (const review of reviews) {
      if (!review.author_name || !review.text || !review.rating) continue;

      // Google gives no review id; author + timestamp is stable for a given review.
      const externalId = `google:${company.googlePlaceId}:${review.author_name}:${review.time ?? 0}`;

      await this.reviewRepository.upsertByExternalId(externalId, {
        source: "GOOGLE",
        authorName: review.author_name,
        authorRole: null,
        rating: Math.round(review.rating),
        text: review.text,
        reviewDate: review.time ? new Date(review.time * 1000) : new Date(),
        sourceUrl: review.author_url ?? company.googleMapsUrl ?? null,
        externalId,
        // Imported reviews go live immediately; unpublish from the admin screen if needed.
        isPublished: true,
      });
      imported += 1;
    }

    const { total } = await this.reviewRepository.list({});
    logger.info({ imported, total }, "Google reviews synced");

    await this.auditService.record("UPDATE_COMPANY_SETTINGS", {
      entityType: "Review",
      newValues: { action: "google-sync", imported },
    });

    return { imported, total };
  }

  private toPersistable(input: ReviewInput): Prisma.ReviewCreateInput {
    return {
      source: input.source,
      authorName: input.authorName.trim(),
      authorRole: input.authorRole?.trim() || null,
      rating: this.assertRating(input.rating),
      text: input.text.trim(),
      reviewDate: input.reviewDate ? new Date(input.reviewDate) : new Date(),
      sourceUrl: input.sourceUrl?.trim() || null,
      isPublished: input.isPublished ?? true,
      sortOrder: input.sortOrder ?? 0,
    };
  }

  private assertRating(rating: number): number {
    const value = Math.round(Number(rating));
    if (!Number.isFinite(value) || value < 1 || value > 5) {
      throw new ValidationError("A rating must be a whole number between 1 and 5");
    }
    return value;
  }
}
